{{ if .Values.vault_up.enabled }}
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: vault-up
  labels:
    {{- include "vault.labels" . | nindent 4 }}
    team: nais
spec:
  image: "{{ .Values.vault_up.image.repository }}/{{ .Values.vault_up.image.name }}:{{ .Values.vault_up.image.tag | default .Chart.AppVersion }}"

  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    path: /metrics
  readiness:
    path: /metrics
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "20m"
      memory: "64Mi"
  vault:
    enabled: true
    paths:
      - kvPath: /secret/aura/vault-up/secret
        mountPath: /var/run/secrets/nais.io/vault-up
{{ end }}
